### ISSUE TITLE
VcXsrv not launching with proper autherization

### ISSUE THREAD

**Issue by naterex23** [jonescompneurolab/hnn#145]
I'm getting the error: 
![image](https://user-images.githubusercontent.com/58052594/69379846-3f43a880-0c7f-11ea-8227-02eb87101a9e.png)

A window quickly pops up indicating an error while executing, but closes almost immediately so I cannot read what the error actually is. I've tried reinstalling and a variety of configs, making sure to select the "disable access control" option as specified. Thus far I have not been able to successfully  open the program. 

Any help would be greatly appreciated.

**Comment by blakecaldwell** [comment]
Thanks for pointing this out. As you already identified, it's some problem with the access control settings. I'm trying to reproduce this on my windows system. Could you send the output of hnn_docker.log (maybe just the last 100 lines or so after a failure)?

**Comment by blakecaldwell** [comment]
@naterex23 I just pushed a code change that will at least give better debugging info. It also has better instructions for windows.

Note that you don't need to start VcXsrv before running the script. Starting and stopping that is handled automatically now.

Could you try the new code:
```
cd hnn
git pull origin master
./hnn_docker.sh -u start
```

And let me know how it goes? If you get a failure still, the output from hnn_docker.log would be a huge help. Thanks!

**Comment by naterex23** [comment]
@blakecaldwell Thanks for the help! 

Unfortunately I'm still getting the same error.  I'm getting an error that --

`C:\Program Files\VcXsrv\xauth.exe:  file C:\Users\NATHANIELREX\.Xauthority does not exist^M             am Files\VcXsrv\system.XWinrc^M                                                                         Warning: Locale not supported by X, falling back to 'C' locale.^M             `

When I search my C drive for this file, I get this weird result that looks like there might be a file, but when I try to open it, I get a warning that it cannot be found and asks if I want to make a new file called ".Xauthority". 

![imma_bout_to_break_something](https://user-images.githubusercontent.com/58052594/70012151-91b77b80-1541-11ea-87e7-0660e993cf5d.PNG)

Attaching .txt of output from the docker log: 
[hnn_docker_log_12_2_19_wow_format_is_BAD_.txt](https://github.com/jonescompneurolab/hnn/files/3914059/hnn_docker_log_12_2_19_wow_format_is_BAD_.txt)

**Comment by blakecaldwell** [comment]
Thanks @naterex23 -- I think this is fixed finally in a new push. About an hour from now, you should be able to use the commands below to try it out.
```
cd hnn
git pull origin master
./hnn_docker.sh -u start
```

**Comment by blakecaldwell** [comment]
@naterex23 I found another bug that may have affected you in #163. Could you let me know if it is working yet?
