### ISSUE TITLE
Mac Install Error

### ISSUE THREAD

**Issue by kohl-carmen** [jonescompneurolab/hnn#256]
Hi everyone,

a new undergrad in the lab, @lzimbalist is struggling to install HNN on her Mac.
She ran:
```
 curl --remote-name https://github.com/jonescompneurolab/hnn/releases/latest/download/hnn.tar.gz
 tar -x --strip-components 1 -f hnn.tar.gz -C hnn_source_code
```
and got the error "tar: could not chdir to 'hnn_source_code"

Can anyone help?
Thanks!

**Comment by blakecaldwell** [comment]
Oh! Looks like a `mkdir hnn_source_code` is missing from the sequence. Try that and then run the `tar` command again.

**Comment by lzimbalist** [comment]
Thanks! That fixes the one error, but now I'm getting:
"tar: Unrecognized archive format
tar: Error exit delayed from previous errors." 
Any ideas how I can fix this one?

**Comment by blakecaldwell** [comment]
Hi @lzimbalist. It seems that there must be something wrong with the `hnn.tar.gz` file. Did the `curl` command complete successfully? Perhaps try removing it and rerunning the commands? Please copy the output here so we can debug. Thanks!

**Comment by lzimbalist** [comment]
Curl did complete successfully. What do you mean by remove it? (rm the whole line or just rerun the rest of the commands without it)

**Comment by blakecaldwell** [comment]
I what thinking `rm hnn.tar.gz` before retrying the commands (`mkdir` is not necessary). However, I think I found the actual issue. Try this `curl` command instead of the one in the instructions.
```
curl -OL https://github.com/jonescompneurolab/hnn/releases/latest/download/hnn.tar.gz
```

**Comment by lzimbalist** [comment]
That fixed it – I'm now up and running. Thank you so much for your help!

**Comment by lzimbalist** [comment]
I seem to be having one other issue now. The GUI opens, but the simulation doesn't actually ever run. When I just try to run the simulation normally, it displays "numprocs = 8" but then nothing happens and when I terminate the simulation the terminal reads:
"Simulation exited with return code -9. Stderr from console:
Warning: could not read file: /Users/lilazimbalist/hnn_out/data/Practice/dpl.txt
Warning: could not read file: /Users/lilazimbalist/hnn_out/data/Practice/spk.txt
Warning: could not read file: /Users/lilazimbalist/hnn_out/data/Practice/dpl.txt
Warning: could not read file: /Users/lilazimbalist/hnn_out/data/Practice/spk.txt"
Any thoughts?

**Comment by blakecaldwell** [comment]
Sorry for the delay in responding to this. It's not immediately clear to me what's going wrong. To get some more information, could you run this command?
```
curl -s "https://raw.githubusercontent.com/jonescompneurolab/hnn/master/installer/mac/check-post.sh" | bash
```

**Comment by lzimbalist** [comment]
This is the output after running the command: 
Performing post-install checks for HNN
--------------------------------------
Checking for XQuartz...ok
Checking if HNN is compiled...ok
Checking for miniconda...ok
Checking for existing python...ok
Checking PATH environment variable for nrniv...ok
Checking PATH environment variable for mpiexec...ok
Checking PYTHONPATH environment variable...failed
Couldn't find NEURON python modules in 
PYTHONPATH=

Checking PYTHONHOME environment variable...ok
Checking NRN_PYLIB environment variable...ok
Checking MPI functionality...ok

(if it helps, I wasn't even able to open the GUI this time – I've noticed every couple of times I go to run the GUI I have to re-run the installation commands before being able to run it)

**Comment by blakecaldwell** [comment]
Okay, that output looks fine. Is there any output in the "Simulation Log" under the "View" many in HNN?

**Comment by lzimbalist** [comment]
When I try to run the GUI now I get this output:
```
File "hnn.py", line 37, in <module>
    runqt5()
  File "hnn.py", line 26, in runqt5
    ex = HNNGUI()
  File "/Users/lilazimbalist/hnn_source_code/hnn_qt5.py", line 3347, in __init__
    self.initUI()
  File "/Users/lilazimbalist/hnn_source_code/hnn_qt5.py", line 4024, in initUI
    self.initSimCanvas(gRow=gRow, reInit=False)
  File "/Users/lilazimbalist/hnn_source_code/hnn_qt5.py", line 4100, in initSimCanvas
    self.m = SIMCanvas(paramf, parent = self, width=10, height=1, dpi=getmplDPI(), optMode=optMode) # also loads data
  File "/Users/lilazimbalist/hnn_source_code/simdat.py", line 276, in __init__
    self.plot()
  File "/Users/lilazimbalist/hnn_source_code/simdat.py", line 756, in plot
    self.plotsimdat()  # creates self.axdipole
  File "/Users/lilazimbalist/hnn_source_code/simdat.py", line 627, in plotsimdat
    (find_param(dfile['outparam'],'save_spec_data') or dinty['Ongoing'] or dinty['Poisson'] or dinty['Tonic'])
  File "/Users/lilazimbalist/hnn_source_code/paramrw.py", line 513, in find_param
    _, p = read(fparam)
  File "/Users/lilazimbalist/hnn_source_code/paramrw.py", line 457, in read
    lines = fio.clean_lines(fparam)
  File "/Users/lilazimbalist/hnn_source_code/fileio.py", line 205, in clean_lines
    with open(file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lilazimbalist/hnn_out/data/default/param.txt'

```

**Comment by lzimbalist** [comment]
Maybe I should try the download from the start? If that's the case, is there anything I definitely need to remove before doing that?

**Comment by blakecaldwell** [comment]
Hi, sorry about this. That issue should be fixed in the next update to HNN. For now, the fix would be to remove files where the simulation output usually gets put: `/Users/lilazimbalist/hnn_out/data/default/`. If that directory doesn't exist, you shouldn't get the error.

**Comment by lzimbalist** [comment]
Yep that fixed the error. My GUI is now up and running but still can't run the simulations. Thanks so much for all of your continued help with this by the way!

**Comment by blakecaldwell** [comment]
Okay, good. What happens if you run
```
mpiexec -np 4 nrniv -mpi run.py
```

This is essentially the command that HNN calls when you click "Run Simulation". All output should go to the console (please copy it here for us to look at). Thanks.

**Comment by lzimbalist** [comment]
`numprocs=4
NEURON -- VERSION 7.8.1-1-gda13bb7c HEAD (da13bb7c) 2020-07-22
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2019
See http://neuron.yale.edu/neuron/credits

Additional mechanisms from files
 mod/ar.mod mod/beforestep_py.mod mod/ca.mod mod/cad.mod mod/cat.mod mod/dipole.mod mod/dipole_pp.mod mod/hh2.mod mod/kca.mod mod/km.mod mod/lfp.mod mod/mea.mod mod/vecevent.mod
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
`

**Comment by blakecaldwell** [comment]
Something looks wrong with the python installation. Wanted to confirm that you ran this command beforehand (and before starting hnn)?
```
source activate hnn
```

**Comment by lzimbalist** [comment]
I did run `source activate hnn` but in order to get the GUI up at all (by running `python hnn.py`) I have to also cd into the hnn_source_code directory – otherwise I get an error

**Comment by blakecaldwell** [comment]
> I did run `source activate hnn` but in order to get the GUI up at all (by running `python hnn.py`) I have to also cd into the hnn_source_code directory – otherwise I get an error
Okay, please try these too:

For debugging:
```
conda list
```

Install numpy directly
```
conda install numpy
```

**Comment by lzimbalist** [comment]
After installing numpy it does now appear when I run `conda list` but still does not run simulations. It looks like I may be working with python v3.7 could that be causing the problem?

**Comment by blakecaldwell** [comment]
Well, that's the right version. So it must be something else with the python environment. Very sorry, but I would recommend abandoning this method and trying the docker installation:
https://github.com/jonescompneurolab/hnn/blob/master/installer/mac/docker-desktop.md

**Comment by lzimbalist** [comment]
Yes ok, thanks so much for all of your help!

**Comment by blakecaldwell** [comment]
@lzimbalist if you have time, would be able to look at the update instructions to see if they help clear up some issues?
https://jonescompneurolab.github.io/hnn/installer/mac/

**Comment by lzimbalist** [comment]
I think that looks good! The only thing I would say is that under "Run the HNN Model" I think the steps should be:
```
source activate hnn
cd hnn_source_code
python hnn.py
```
(at least that's the only way I was able to do it)
